#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
feh --bg-scale /home/dawn/Pictures/hot-air-balloon-x-wallpaper.jpg 
setxkbmap ch &
$HOME/.config/polybar/launch.sh bspwm rounded &
picom -f &
dunst &
conky -q -c /home/dawn/.config/conky/conky.conf &
eval $(gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK
bsp-layout set tall &

bspc config split_ratio          0.52
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true
bspc config window_gap 20
bspc config border_width 0
bspc config border_radius 10

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a conky state=floating manage=off
bspc rule -a feh state=floating follow=on 
bspc rule -a galculator state=floating

betterlockscreen -u /home/dawn/Pictures/keyz.png &
/home/dawn/CustomScripts/bspwm/lock.sh &
